[package]
name = "re-reg"
version = "0.1.0"
edition = "2021"
authors = ["cyvb"]

[profile.test]
opt-level = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]
